/**
 * Standardized Error Codes
 */

export const ErrorCodes = {
    // Authentication Errors
    AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
    AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
    AUTH_MISSING_TOKEN: 'AUTH_MISSING_TOKEN',
    AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
    AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
    AUTH_WALLET_VERIFICATION_FAILED: 'AUTH_WALLET_VERIFICATION_FAILED',

    // Validation Errors
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    INVALID_INPUT: 'INVALID_INPUT',
    MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',

    // Resource Errors
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
    RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
    RESOURCE_ACCESS_DENIED: 'RESOURCE_ACCESS_DENIED',

    // Server Errors
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    DATABASE_ERROR: 'DATABASE_ERROR',
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

    // Rate Limiting
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
};

export const ErrorMessages = {
    [ErrorCodes.INTERNAL_SERVER_ERROR]: 'An unexpected error occurred',
    [ErrorCodes.VALIDATION_ERROR]: 'Validation failed',
    [ErrorCodes.RESOURCE_NOT_FOUND]: 'Resource not found',
};
